### ISSUE TITLE
Model loaded from Checkpoint differ in Master and Development branch

### ISSUE THREAD

**Issue by arrjon** [stefanradev93/BayesFlow#58]
Trained models saved in the master branch and then loaded within the development branch do not give the same results.

I tested it using the [Intro_Amortized_Posterior_Estimation](https://github.com/stefanradev93/BayesFlow/blob/7c4de55e942cd44f115a66d3714d35d8403fd0a0/docs/source/tutorial_notebooks/Intro_Amortized_Posterior_Estimation.ipynb)-notebook in a clean install of the Master branch and saved the model by providing the ```checkpoint_path``` argument for the ```Trainer```. Then I loaded the model within a clean install of the Development branch where I only skipped the online training cell.

All the diagnostics plots in the notebook changed significantly. Most prominently the ```plot_recovery``` as can be seen in the attached images.

Master branch
![recovery_plot_master_branch](https://user-images.githubusercontent.com/69197639/217518138-3380a5b6-7cfe-48e1-9e3a-b7ee625ca0e0.png)

Development branch
![recovery_plot_development_branch](https://user-images.githubusercontent.com/69197639/217518150-7aadbdd5-01dc-476b-aa25-b8c4f3fdcb31.png)

However, retrain the model on the Development branch gives the correct results like in the Master branch. Hence, it seems like the branches have different defaults somewhere, which would be interesting to know.

**Comment by stefanradev93** [comment]
Hi Jonas, nice spot! Are you using the most recent versions of both branches?

**Comment by stefanradev93** [comment]
I found out the reason why that happens even though defaults are the same across branches. Development will allow the use of residual coupling blocks, which outsourced the output layer of the block outside the internal `Sequential` network. TensorFlow does not know how to assign the weights for that new layer after loading. I will re-write the addition in a backward-compatible manner.

**Comment by stefanradev93** [comment]
I pushed a preliminary fix. Could you try to reproduce the bug with the current state of the Development branch? :)

**Comment by arrjon** [comment]
The preliminary fix works nicely. Issue seems to be solved!

**Comment by arrjon** [comment]
FYI: If one tries to use the `trainer.checkpoint.restore` function to restore a former checkpoint after the `trainer = Trainer(...)` has been already initialised, the problem still exists. However, this function is probably not meant to be called outside the class.
